var searchData=
[
  ['example_20_26_20tutorial_20projects',['Example &amp; Tutorial Projects',['../example_tutorial_projects.html',1,'']]],
  ['example_20_28jkqtplotter_29_3a_20cmake_20example',['Example (JKQTPlotter): CMake Example',['../_j_k_q_t_c_make_link_example.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtfastplotter_29',['Example (JKQTFastPlotter)',['../_j_k_q_t_fast_plotter_test.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtmathtext_29_3a_20a_20simple_20usage_20example',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtmathtext_29_3a_20a_20test_20application',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20advanced_20line_20and_20fill_20styling',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20barchart',['Example (JKQTPlotter): Simple barchart',['../_j_k_q_t_plotter_barcharts.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20boxplots',['Example (JKQTPlotter): Boxplots',['../_j_k_q_t_plotter_boxplots_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20styling_20different_20aspects_20of_20boxplots',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20contour_20plots',['Example (JKQTPlotter): Contour Plots',['../_j_k_q_t_plotter_contour_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20date_2ftime_20axes',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20plotting_20a_20statistical_20distribution_20of_20data',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20different_20types_20of_20errorindicators',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20filled_20curve_20plots',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20plotting_20mathematical_20functions_20as_20line_20graphs',['Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20plotting_20geometric_20objects',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20math_20image_20plot',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20math_20image_20plot_20with_20modifier_20datat',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20math_20image_20plot_2c_20showin_20a_201_2dchannel_20opencv_20cv_3a_3amat',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20qimage_20as_20a_20graph',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20rgb_20image_20plot_2c_20showing_20a_203_2dchannel_20opencv_20cv_3a_3amat',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20image_20plots_20with_20custom_20palettes',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20impulse_20plots',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20line_20graph_20with_20logarithmic_20y_2daxis',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20laying_20out_20several_20plots',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20plotting_20parametric_20curves',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20scatter_20graph_20with_20parametrized_20symbols_2fcolors',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20draw_20an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20plotting_20parsed_20mathematical_20functions_20as_20line_20graphs',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20math_20rgb_2fcmy_20image_20plot',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20very_20simple_20line_2dgraph',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20step_20line_20plots_20in_20different_20styles',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20line_2dgraph_20with_20live_2ddata_20_28speed_20test_29',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20stacked_20barchart',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20line_20graph_20with_20different_20symbols_20and_20line_20styles',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20simple_20line_2dgraph_20with_20error_20bars',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['example_20_28jkqtplotter_29_3a_20violin_20plots',['Example (JKQTPlotter): Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html',1,'exampleTutorialProjects']]]
];
